import { mutation } from "./_generated/server";

type SeedRow = {
  title: string;
  organization: string;
  description: string;
  requiredSkills: string[];
  preferredSkills: string[];
  location: string;
  duration: string;
  stipend: string;
  type: string;
  status: "open";
  deadline: number;
  contactEmail: string;
  postedAt: number;
};

// Batch 3: 50 additional Ayurveda-related internships. The mutation is fully
// idempotent — it only inserts roles whose title is not already present, so
// running it on a fresh DB or one already carrying batches 1 & 2 is safe.
export const seedMore2 = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("internships").collect();
    const have = new Set(existing.map((i) => i.title.trim().toLowerCase()));

    const now = Date.now();
    const d = (days: number) => now + days * 24 * 60 * 60 * 1000;
    const p = (days: number) => now - days * 24 * 60 * 60 * 1000;

    const internships: SeedRow[] = [
      {
        title: "Clinical Protocol Writing Intern",
        organization: "National Institute of Ayurveda (NIA), Jaipur",
        description:
          "Draft and review clinical study protocols for Ayurvedic interventions in lifestyle disorders, including objective, design, eligibility and statistical sections for ethics committee submission.",
        requiredSkills: ["Clinical Research", "Report Writing", "Ayurvedic Medicine"],
        preferredSkills: ["Academic Writing", "Literature Review", "Statistics"],
        location: "Jaipur, Rajasthan",
        duration: "3 months",
        stipend: "₹10,000/month",
        type: "Research",
        status: "open",
        deadline: d(40),
        contactEmail: "clinical@nia-jaipur.com",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Tribal Health Survey Intern",
        organization: "Regional Ayurveda Research Institute (RARI), Thiruvananthapuram",
        description:
          "Participate in community health surveys among tribal populations, document traditional health practices, and help prepare district-level AYUSH health utilization reports.",
        requiredSkills: ["Community Health", "Data Collection", "Report Writing"],
        preferredSkills: ["Public Health", "Social Work", "MS Excel"],
        location: "Thiruvananthapuram, Kerala",
        duration: "6 months",
        stipend: "₹12,000/month + Travel Allowance",
        type: "Government",
        status: "open",
        deadline: d(55),
        contactEmail: "surveys@rari-kerala.gov.in",
        postedAt: p(4),
      },
      {
        title: "Herbal Drug Interaction Research Intern",
        organization: "SDM College of Ayurveda, Udupi",
        description:
          "Study herb-drug and herb-herb interactions of commonly prescribed Ayurvedic formulations, compile published evidence, and assist in drafting interaction-awareness materials for prescribers.",
        requiredSkills: ["Herbal Medicine", "Literature Review", "Ayurvedic Medicine"],
        preferredSkills: ["Pharmacology", "Academic Writing", "Data Analysis"],
        location: "Udupi, Karnataka",
        duration: "6 months",
        stipend: "₹11,000/month",
        type: "Research",
        status: "open",
        deadline: d(50),
        contactEmail: "research@sdmcau.org",
        postedAt: p(6),
      },
      {
        title: "Rasayana Drug Development Intern",
        organization: "Aimil Pharmaceuticals",
        description:
          "Support pre-clinical and clinical development of Rasayana (rejuvenative) formulations — assist in dose fixation studies, literature dossiers, and regulatory dossier preparation for new herbal products.",
        requiredSkills: ["Rasashastra", "Ayurvedic Medicine", "Quality Control"],
        preferredSkills: ["Clinical Research", "GMP", "Medical Writing"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Industry",
        status: "open",
        deadline: d(60),
        contactEmail: "rd@aimilpharma.com",
        postedAt: p(5),
      },
      {
        title: "Ayurveda Analytical Method Validation Intern",
        organization: "CSIR-CIMAP, Lucknow",
        description:
          "Validate HPLC/HPTLC methods for marker-based standardization of herbal raw materials and formulations, maintain analytical records, and help troubleshoot method robustness issues.",
        requiredSkills: ["Analytical Chemistry", "Laboratory Skills", "HPLC"],
        preferredSkills: ["HPTLC", "Quality Control", "Statistics"],
        location: "Lucknow, Uttar Pradesh",
        duration: "6 months",
        stipend: "₹16,000/month",
        type: "Research",
        status: "open",
        deadline: d(45),
        contactEmail: "analytical@cimap.res.in",
        postedAt: p(3),
      },
      {
        title: "BAMS Clinical Case Documentation Intern",
          organization: "Parul Institute of Ayurveda, Vadodara",
        description:
          "Document comprehensive clinical case records of chronic disease patients under Kayachikitsa treatment, digitize case files, and assist in building a searchable case repository for teaching.",
        requiredSkills: ["Kayachikitsa", "Patient Care", "Data Entry"],
        preferredSkills: ["Medical Writing", "MS Excel", "Report Writing"],
        location: "Vadodara, Gujarat",
        duration: "6 months",
        stipend: "₹8,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(40),
        contactEmail: "cases@pia.edu.in",
        postedAt: p(7),
      },
      {
        title: "Marma Therapy Research Intern",
        organization: "Kerala Ayurveda Academy, Kochi",
        description:
          "Assist clinical research on Marma chikitsa for musculoskeletal pain, collect patient-reported outcome data, and help standardize marma point assessment documentation.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Data Collection"],
        preferredSkills: ["Clinical Research", "Statistics", "SPSS"],
        location: "Kochi, Kerala",
        duration: "3 months",
        stipend: "₹9,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(35),
        contactEmail: "marma@keralaayurveda.academy",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Digital Health & mHealth Intern",
        organization: "Apollo AyurVAID",
        description:
          "Help design digital patient journeys for Ayurvedic chronic-care programs, assist in building health-risk questionnaires, and evaluate telehealth follow-up workflows for NCD patients.",
        requiredSkills: ["Ayurvedic Medicine", "Data Entry", "Communication"],
        preferredSkills: ["Health Informatics", "MS Excel", "Data Visualization"],
        location: "Bengaluru (Hybrid)",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "digital@ayurvaid.com",
        postedAt: p(1),
      },
      {
        title: "Garbhini Paricharya Antenatal Intern",
        organization: "Ayurveda Maternity & Women's Health Centre, Mumbai",
        description:
          "Observe and assist antenatal OPD following Garbhini Paricharya protocols, document monthly trimester assessment data, and prepare patient education kits for safe Ayurvedic pregnancy care.",
        requiredSkills: ["Prasuti Tantra", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Data Collection", "Content Writing", "Communication"],
        location: "Mumbai, Maharashtra",
        duration: "6 months",
        stipend: "₹9,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(45),
        contactEmail: "antenatal@ayurmaternity.in",
        postedAt: p(5),
      },
      {
        title: "Ayurveda Cosmeceutical Stability Intern",
        organization: "Just Herbs (Nature's Essence Pvt. Ltd.)",
        description:
          "Run accelerated and real-time stability studies for Ayurvedic skincare formulations, monitor pH/viscosity/microbial parameters, and document shelf-life recommendations for regulatory filings.",
        requiredSkills: ["Quality Control", "Laboratory Skills", "Herbal Medicine"],
        preferredSkills: ["HPLC", "GMP", "Analytical Chemistry"],
        location: "Gurugram, Haryana",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Industry",
        status: "open",
        deadline: d(35),
        contactEmail: "stability@justherbs.in",
        postedAt: p(2),
      },
      {
        title: "Sowa-Rigpa & AYUSH Comparative Research Intern",
        organization: "Central Council for Research in Ayurvedic Sciences (CCRAS)",
        description:
          "Compare pharmacopeial standards and therapeutic classifications across AYUSH systems (Ayurveda, Sowa-Rigpa, Unani, Siddha), and help prepare a cross-system reference document for researchers.",
        requiredSkills: ["Literature Review", "Ayurvedic Medicine", "Academic Writing"],
        preferredSkills: ["Pharmacognosy", "Data Entry", "Report Writing"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹17,000/month",
        type: "Research",
        status: "open",
        deadline: d(65),
        contactEmail: "comparative@ccras.res.in",
        postedAt: p(8),
      },
      {
        title: "AYUSH School Health Program Intern",
        organization: "State AYUSH Mission, Uttarakhand",
        description:
          "Support school-level yoga and nutrition awareness camps, collect anthropometric and wellness data from students, and evaluate program outcomes against AYUSH school health guidelines.",
        requiredSkills: ["Yoga", "Community Health", "Data Collection"],
        preferredSkills: ["Public Health", "MS Excel", "Report Writing"],
        location: "Dehradun, Uttarakhand",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Government",
        status: "open",
        deadline: d(40),
        contactEmail: "schoolhealth@ayushuk.gov.in",
        postedAt: p(3),
      },
      {
        title: "Medicinal Plant DNA Barcoding Intern",
        organization: "Institute of Bioresources & Sustainable Development (IBSD), Imphal",
        description:
          "Extract genomic DNA from medicinal plants used in Ayurveda, perform PCR amplification and sequencing of barcode regions, and help build a reference library for raw-material authentication.",
        requiredSkills: ["Laboratory Skills", "Botany", "Data Analysis"],
        preferredSkills: ["Bioinformatics", "Molecular Biology", "Python"],
        location: "Imphal, Manipur",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Research",
        status: "open",
        deadline: d(55),
        contactEmail: "dnabarcode@ibsd.gov.in",
        postedAt: p(7),
      },
      {
        title: "Shirodhara & Basti Therapy Clinical Intern",
        organization: "Vishwas Ayurveda Panchakarma Centre, Nashik",
        description:
          "Assist senior therapists in Shirodhara, Basti and Pinda Sweda procedures, record treatment responses, and help maintain therapy protocols for stress and neurological case management.",
        requiredSkills: ["Panchakarma", "Patient Care", "Ayurvedic Medicine"],
        preferredSkills: ["Massage Therapy", "Data Collection", "Communication"],
        location: "Nashik, Maharashtra",
        duration: "6 months",
        stipend: "₹8,000/month + Accommodation",
        type: "Clinical",
        status: "open",
        deadline: d(50),
        contactEmail: "therapies@vishwasayurveda.in",
        postedAt: p(4),
      },
      {
        title: "Ayurveda Nutrition Labeling Compliance Intern",
        organization: "Kapiva Ayurveda",
        description:
          "Audit product nutrition and ingredient labels against FSSAI and AYUSH license norms, prepare compliance matrices, and coordinate corrections with the product and legal teams.",
        requiredSkills: ["Ayurvedic Medicine", "Quality Control", "Data Entry"],
        preferredSkills: ["Regulatory Affairs", "MS Excel", "Report Writing"],
        location: "Bengaluru (Hybrid)",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open",
        deadline: d(25),
        contactEmail: "compliance@kapiva.in",
        postedAt: p(1),
      },
      {
        title: "Ayurgenomics Prakriti Phenotyping Intern",
        organization: "CSIR-IGIB Ayurgenomics Unit, New Delhi",
        description:
          "Administer validated Prakriti assessment questionnaires, collect anthropometric and biochemical phenotype data, and assist in correlating Prakriti types with genotypic markers.",
        requiredSkills: ["Ayurvedic Medicine", "Data Collection", "Statistics"],
        preferredSkills: ["Python", "Bioinformatics", "R"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹22,000/month",
        type: "Research",
        status: "open",
        deadline: d(60),
        contactEmail: "ayurgenomics@igib.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Hospital Operations Intern",
        organization: "Sanjivani Ayurvedic Hospital, Patna",
        description:
          "Rotate through OPD scheduling, pharmacy inventory and patient admission workflows, analyze consultation loads, and propose process improvements for hospital administration.",
        requiredSkills: ["Communication", "MS Excel", "Data Entry"],
        preferredSkills: ["Operations Management", "Customer Service", "Report Writing"],
        location: "Patna, Bihar",
        duration: "3 months",
        stipend: "₹7,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(30),
        contactEmail: "admin@sanjivaniayurveda.org",
        postedAt: p(2),
      },
      {
        title: "Traditional Knowledge Digital Library Annotation Intern",
        organization: "CSIR-TKDL Unit, New Delhi",
        description:
          "Annotate and validate Ayurvedic formulations from classical texts for the TKDL database, cross-check Sanskrit shloka translations, and support patent-examiner search assistance workflows.",
        requiredSkills: ["Ayurvedic Medicine", "Data Entry", "Literature Review"],
        preferredSkills: ["Sanskrit", "Siddha Medicine", "Academic Writing"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹18,000/month",
        type: "Government",
        status: "open",
        deadline: d(70),
        contactEmail: "annotation@tkdl.res.in",
        postedAt: p(9),
      },
      {
        title: "Herbal Nursery & Good Agricultural Practices Intern",
        organization: "Maharashtra State Medicinal Plants Board, Pune",
        description:
          "Support certified nursery operations for Ashwagandha, Shatavari and Giloy saplings, monitor GAP compliance, and document post-harvest handling practices for farmer training programs.",
        requiredSkills: ["Botany", "Herbal Medicine", "Laboratory Skills"],
        preferredSkills: ["Agriculture", "Soil Science", "Report Writing"],
        location: "Pune, Maharashtra",
        duration: "6 months",
        stipend: "₹10,000/month + Field Allowance",
        type: "Government",
        status: "open",
        deadline: d(60),
        contactEmail: "nursery@msmpb.org",
        postedAt: p(5),
      },
      {
        title: "AYUSH Pharmacovigilance Data Analyst Intern",
        organization: "Ayush Pharmacovigilance Cell, Gujarat",
        description:
          "Clean and analyse adverse-event reports for AYUSH products, run causality assessments under supervision, and prepare quarterly signal review summaries for the state pharmacovigilance cell.",
        requiredSkills: ["Data Analysis", "Report Writing", "Ayurvedic Medicine"],
        preferredSkills: ["SPSS", "MS Excel", "Pharmacovigilance"],
        location: "Gandhinagar, Gujarat",
        duration: "6 months",
        stipend: "₹13,000/month",
        type: "Government",
        status: "open",
        deadline: d(50),
        contactEmail: "pvcell@gujarat.gov.in",
        postedAt: p(4),
      },
      {
        title: "Vrana Ropana Wound Healing Research Intern",
        organization: "JSS Ayurveda Medical College, Mysuru",
        description:
          "Assist clinical evaluation of Ayurvedic wound-care formulations (Jatyadi taila variants) in chronic ulcer cases, document healing progress with standardized scales, and compile outcome data.",
        requiredSkills: ["Shalya Tantra", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Clinical Research", "Data Analysis", "Medical Writing"],
        location: "Mysuru, Karnataka",
        duration: "6 months",
        stipend: "₹9,000/month",
        type: "Research",
        status: "open",
        deadline: d(45),
        contactEmail: "woundcare@jssamc.edu.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Brand & Packaging Design Intern",
        organization: "Dhathri Ayurveda, Coimbatore",
        description:
          "Design packaging and brand assets for new Ayurvedic product lines, prepare artwork for regulatory review, and support A/B testing of pack communication with retail teams.",
        requiredSkills: ["Content Writing", "Communication", "Digital Marketing"],
        preferredSkills: ["Graphic Design", "Canva", "Social Media"],
        location: "Coimbatore, Tamil Nadu",
        duration: "3 months",
        stipend: "₹11,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "design@dhathri.in",
        postedAt: p(2),
      },
      {
        title: "Panchagavya Product Formulation Intern",
        organization: "Go-Vigyan Anusandhan Kendra, Nagpur",
        description:
          "Develop and standardize Panchagavya-based formulations for soil health and animal care, run physico-chemical analysis batches, and document formulation protocols for field validation.",
        requiredSkills: ["Herbal Medicine", "Laboratory Skills", "Quality Control"],
        preferredSkills: ["Agriculture", "Phytochemistry", "GMP"],
        location: "Nagpur, Maharashtra",
        duration: "6 months",
        stipend: "₹10,000/month + Accommodation",
        type: "Research",
        status: "open",
        deadline: d(55),
        contactEmail: "research@govigyan.org",
        postedAt: p(7),
      },
      {
        title: "AYUSH Health Insurance Policy Research Intern",
        organization: "National Insurance Academy, Pune",
        description:
          "Analyse insurance claim data and market surveys to model coverage scenarios for AYUSH treatments, review international integrative-medicine insurance models, and draft policy recommendation briefs.",
        requiredSkills: ["Public Health", "Data Analysis", "Report Writing"],
        preferredSkills: ["MS Excel", "Economics", "Power BI"],
        location: "Pune, Maharashtra",
        duration: "3 months",
        stipend: "₹15,000/month",
        type: "Government",
        status: "open",
        deadline: d(35),
        contactEmail: "healthresearch@niapune.org",
        postedAt: p(3),
      },
      {
        title: "Prakriti Assessment Clinic Intern",
        organization: "Jiva Ayurveda — Prakriti Division, Faridabad",
        description:
          "Assist in running Prakriti assessment consultations, validate digital questionnaire outputs against physician assessments, and help personalize dinacharya recommendations for patients.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Communication"],
        preferredSkills: ["Data Entry", "Content Writing", "MS Excel"],
        location: "Faridabad, Haryana (Hybrid)",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "prakriti@jiva.com",
        postedAt: p(1),
      },
      {
        title: "Ayurveda Scientific Journal Editorial Intern",
        organization: "Ayu Journal (Peer-Reviewed Ayurveda Publication), New Delhi",
        description:
          "Support manuscript triage, reference formatting, plagiarism screening and reviewer coordination for an indexed Ayurveda research journal, and learn journalistic standards of scientific publishing.",
        requiredSkills: ["Academic Writing", "Literature Review", "Medical Writing"],
        preferredSkills: ["Report Writing", "MS Excel", "Communication"],
        location: "New Delhi (Remote OK)",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Research",
        status: "open",
        deadline: d(60),
        contactEmail: "editorial@ayujournal.org",
        postedAt: p(5),
      },
      {
        title: "Sandalwood & Agarwood Agronomy Intern",
        organization: "Institute of Wood Science & Technology, Bengaluru",
        description:
          "Monitor growth trials of sandalwood and agarwood plantations used in Ayurvedic formulations, record phenological data, and assist in heartwood induction experiments.",
        requiredSkills: ["Botany", "Laboratory Skills", "Data Entry"],
        preferredSkills: ["Agriculture", "Soil Science", "Statistics"],
        location: "Bengaluru, Karnataka",
        duration: "6 months",
        stipend: "₹14,000/month",
        type: "Research",
        status: "open",
        deadline: d(65),
        contactEmail: "agronomy@iwst.res.in",
        postedAt: p(8),
      },
      {
        title: "Ayurveda Cold-Chain & Logistics Intern",
        organization: "Nisarg Organic Farm & Herbals, Nashik",
        description:
          "Design temperature-monitored logistics flows for fresh herbal extracts and finished Ayurvedic products, audit cold-chain vendors, and prepare transport-validation reports.",
        requiredSkills: ["Quality Control", "Data Entry", "MS Excel"],
        preferredSkills: ["Supply Chain Management", "GMP", "Report Writing"],
        location: "Nashik, Maharashtra",
        duration: "3 months",
        stipend: "₹11,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "logistics@nisargherbals.com",
        postedAt: p(2),
      },
      {
        title: "Tribal Health & AYUSH Field Research Intern",
        organization: "National Institute for Research in Tribal Health (NIRTH), Jabalpur",
        description:
          "Deploy in tribal health camps to document AYUSH awareness and usage patterns, collect qualitative interviews, and help draft an implementation report for AYUSH service delivery in tribal districts.",
        requiredSkills: ["Community Health", "Public Health", "Data Collection"],
        preferredSkills: ["Social Work", "Report Writing", "Hindi"],
        location: "Jabalpur, Madhya Pradesh + Field Sites",
        duration: "6 months",
        stipend: "₹15,000/month + Travel Allowance",
        type: "Government",
        status: "open",
        deadline: d(70),
        contactEmail: "field@nirth.res.in",
        postedAt: p(9),
      },
      {
        title: "Ayurveda Systematic Review Intern",
        organization: "Center for Integrative Medicine & Research, Manipal",
        description:
          "Conduct systematic reviews and meta-analyses of Ayurvedic interventions for metabolic syndrome, screen databases, extract data, and perform risk-of-bias assessments with senior methodologists.",
        requiredSkills: ["Literature Review", "Research Methodology", "Data Analysis"],
        preferredSkills: ["Statistics", "R", "Academic Writing"],
        location: "Manipal, Karnataka (Hybrid)",
        duration: "6 months",
        stipend: "₹16,000/month",
        type: "Research",
        status: "open",
        deadline: d(55),
        contactEmail: "reviews@cimr.manipal.edu",
        postedAt: p(6),
      },
      {
        title: "Kriyakalpa Netra Chikitsa Intern",
        organization: "Vaidyaratnam Oushadhasala Eye Clinic, Thrissur",
        description:
          "Observe and assist Kriyakalpa procedures for eye disorders — Tarpana, Putapaka, Anjana and Seka — document visual-acuity outcome data, and learn in-house medicine preparation for eye care.",
        requiredSkills: ["Shalakya Tantra", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Clinical Research", "Data Entry", "Pharmacognosy"],
        location: "Thrissur, Kerala",
        duration: "6 months",
        stipend: "₹9,000/month + Accommodation",
        type: "Clinical",
        status: "open",
        deadline: d(50),
        contactEmail: "eyecare@vaidyaratnam.in",
        postedAt: p(4),
      },
      {
        title: "Astanga Hrudaya Manuscript Translation Intern",
        organization: "National Institute of Indian Medical Heritage, Hyderabad",
        description:
          "Transliterate and annotate chapters of classical Ayurvedic manuscripts, verify Sanskrit terminology against standard lexicons, and help build a bilingual glossary for heritage documentation.",
        requiredSkills: ["Ayurvedic Medicine", "Literature Review", "Data Entry"],
        preferredSkills: ["Sanskrit", "Academic Writing", "Content Writing"],
        location: "Hyderabad, Telangana",
        duration: "6 months",
        stipend: "₹13,000/month",
        type: "Government",
        status: "open",
        deadline: d(65),
        contactEmail: "heritage@niimh.gov.in",
        postedAt: p(8),
      },
      {
        title: "Ayurveda Hospital Digital Marketing Intern",
        organization: "Ayurleaf Wellness Hospital, Bengaluru",
        description:
          "Plan and run wellness-hospital digital campaigns across Google and social channels, write SEO content for treatment pages, and report on patient-acquisition metrics weekly.",
        requiredSkills: ["Digital Marketing", "Content Writing", "Communication"],
        preferredSkills: ["SEO", "Social Media", "Data Visualization"],
        location: "Bengaluru (Hybrid)",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Industry",
        status: "open",
        deadline: d(25),
        contactEmail: "marketing@ayurleaf.in",
        postedAt: p(1),
      },
      {
        title: "Bhasma Particle Characterization Intern",
        organization: "Institute of Ayurvedic Sciences & Nanotechnology, Pune",
        description:
          "Characterize Ayurvedic Bhasma preparations using particle-size analysis, XRD and electron microscopy, correlate physical parameters with classical Shodhana-Marana processing, and document findings.",
        requiredSkills: ["Rasashastra", "Laboratory Skills", "Analytical Chemistry"],
        preferredSkills: ["Nanotechnology", "Data Analysis", "Report Writing"],
        location: "Pune, Maharashtra",
        duration: "6 months",
        stipend: "₹16,000/month",
        type: "Research",
        status: "open",
        deadline: d(55),
        contactEmail: "bhasma@iasn.in",
        postedAt: p(5),
      },
      {
        title: "Dinacharya & Ritucharya School Program Intern",
        organization: "Rashtriya Ayurveda Vidyapeeth, New Delhi",
        description:
          "Pilot daily-routine and seasonal-regimen modules in partner schools, collect student wellness surveys, and help build teacher toolkits on Dinacharya and Ritucharya for urban classrooms.",
        requiredSkills: ["Ayurvedic Medicine", "Yoga", "Community Health"],
        preferredSkills: ["Content Writing", "Event Management", "MS Excel"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Government",
        status: "open",
        deadline: d(35),
        contactEmail: "schools@ravdelhi.nic.in",
        postedAt: p(3),
      },
      {
        title: "Ayurveda Clinical Skills OSCE Development Intern",
        organization: "Ayurveda Education Cell, Banaras Hindu University",
        description:
          "Help design Objective Structured Clinical Examination (OSCE) stations for BAMS final-year skills — Nadi Pariksha, assessment of Prakriti, and basic Panchakarma techniques — including scoring rubrics.",
        requiredSkills: ["Ayurvedic Medicine", "Academic Writing", "Communication"],
        preferredSkills: ["Education Design", "Content Writing", "Kayachikitsa"],
        location: "Varanasi, Uttar Pradesh",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Research",
        status: "open",
        deadline: d(60),
        contactEmail: "osce@bhuayurveda.in",
        postedAt: p(6),
      },
      {
        title: "Herbarium Curation Intern",
        organization: "Blatter Herbarium, St. Xavier's College, Mumbai",
        description:
          "Catalogue medicinal plant specimens used in Ayurvedic pharmacopoeias, digitize label data, georeference collection sites, and prepare identification keys for commonly traded raw drugs.",
        requiredSkills: ["Botany", "Herbal Medicine", "Data Entry"],
        preferredSkills: ["Taxonomy", "GIS Mapping", "Photography"],
        location: "Mumbai, Maharashtra",
        duration: "6 months",
        stipend: "₹8,000/month",
        type: "Research",
        status: "open",
        deadline: d(70),
        contactEmail: "herbarium@xaviers.edu",
        postedAt: p(7),
      },
      {
        title: "AYUSH Startup Mentorship Program Intern",
        organization: "AYUSH Startup Incubator, AIIA New Delhi",
        description:
          "Support cohort operations for AYUSH health-tech startups — organize mentor sessions, track startup milestones, and prepare investor-readiness summaries for incubated ventures.",
        requiredSkills: ["Communication", "Event Management", "Report Writing"],
        preferredSkills: ["Digital Marketing", "Data Entry", "MS Excel"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "incubator@aiia.gov.in",
        postedAt: p(2),
      },
      {
        title: "Srotas & Metabolic Health Case Study Intern",
        organization: "Ayurveda Metabolic Clinic, Hyderabad",
        description:
          "Follow patients on Ayurvedic metabolic therapy for diabetes and dyslipidemia, document Srotas-based assessments and lab trends, and co-author clinical case reports with the treating physicians.",
        requiredSkills: ["Kayachikitsa", "Patient Care", "Data Collection"],
        preferredSkills: ["Clinical Research", "Medical Writing", "Statistics"],
        location: "Hyderabad, Telangana",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(50),
        contactEmail: "metabolic@ayurclinic.in",
        postedAt: p(4),
      },
      {
        title: "Ayurvedic Oral Care Clinical Trial Intern",
        organization: "AIMIL Clinical Research Cell, Jaipur",
        description:
          "Coordinate a clinical trial of an Ayurvedic toothpaste and mouthwash for gingivitis — schedule participant visits, administer oral-health indices, and maintain source documents under GCP.",
        requiredSkills: ["Clinical Research", "Patient Care", "Data Entry"],
        preferredSkills: ["GCP", "SPSS", "Medical Writing"],
        location: "Jaipur, Rajasthan",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Industry",
        status: "open",
        deadline: d(55),
        contactEmail: "trials@aimilcare.com",
        postedAt: p(5),
      },
      {
        title: "Ayurvedic Hospital Rotational Intern",
        organization: "Sri Ganganagar Ayurvedic Medical College & Hospital, Punjab",
        description:
          "Complete supervised rotations across Kayachikitsa, Panchakarma, Shalya and Prasuti departments, maintain rotation logbooks, and present weekly case discussions in departmental seminars.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Panchakarma"],
        preferredSkills: ["Communication", "Clinical Research", "Kayachikitsa"],
        location: "Sri Ganganagar, Rajasthan",
        duration: "6 months",
        stipend: "₹8,000/month",
        type: "Clinical",
        status: "open",
        deadline: d(60),
        contactEmail: "rotations@sgamch.org",
        postedAt: p(6),
      },
      {
        title: "Medicinal Plant Essential Oil Extraction Intern",
        organization: "Fragrance & Flavour Development Centre, Kannauj",
        description:
          "Operate pilot-scale steam-distillation units for Ayurvedic aromatic herbs (Tulsi, Lemongrass, Vetiver), optimize extraction yields, and analyse oil composition by GC for quality documentation.",
        requiredSkills: ["Herbal Extraction", "Laboratory Skills", "Phytochemistry"],
        preferredSkills: ["Analytical Chemistry", "Quality Control", "Data Entry"],
        location: "Kannauj, Uttar Pradesh",
        duration: "6 months",
        stipend: "₹12,000/month",
        type: "Government",
        status: "open",
        deadline: d(60),
        contactEmail: "distillation@ffdc.gov.in",
        postedAt: p(5),
      },
      {
        title: "AYUSH Policy Data Visualization Intern",
        organization: "NITI Aayog Health Vertical, New Delhi",
        description:
          "Build interactive dashboards on AYUSH budgetary allocation, institutional infrastructure and workforce data for policy monitoring, and contribute to analytical chapters of health reports.",
        requiredSkills: ["Data Visualization", "Report Writing", "MS Excel"],
        preferredSkills: ["Power BI", "Tableau", "Python"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹20,000/month",
        type: "Government",
        status: "open",
        deadline: d(35),
        contactEmail: "healthdata@niti.gov.in",
        postedAt: p(3),
      },
      {
        title: "Green Pharmacy Cultivation Intern",
        organization: "State Medicinal Plant Board, Chhattisgarh",
        description:
          "Establish organic cultivation plots for high-demand Ayurvedic herbs, train farmer groups in organic certification processes, and document year-round agronomy calendars for tribal belts.",
        requiredSkills: ["Botany", "Community Health", "Herbal Medicine"],
        preferredSkills: ["Agriculture", "Social Work", "Report Writing"],
        location: "Raipur, Chhattisgarh + Field Sites",
        duration: "6 months",
        stipend: "₹12,000/month + Field Allowance",
        type: "Government",
        status: "open",
        deadline: d(70),
        contactEmail: "greenpharmacy@cgmpb.org",
        postedAt: p(7),
      },
      {
        title: "Yoga Nidra & Sleep Research Intern",
        organization: "All India Institute of Medical Sciences, Rishikesh — Yoga & Lifestyle Lab",
        description:
          "Support clinical studies evaluating Yoga Nidra for insomnia and anxiety — administer PSQI and actigraphy protocols, manage participant schedules, and assist in physiological data collection.",
        requiredSkills: ["Yoga", "Clinical Research", "Data Collection"],
        preferredSkills: ["Statistics", "Psychology", "SPSS"],
        location: "Rishikesh, Uttarakhand",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Research",
        status: "open",
        deadline: d(55),
        contactEmail: "yogalab@aiimsrishikesh.edu.in",
        postedAt: p(4),
      },
      {
        title: "Ayurvedic Soap & Personal Care R&D Intern",
        organization: "Kama Ayurveda, New Delhi",
        description:
          "Assist the R&D lab in batch trials of herbal soaps and body oils, evaluate organoleptic and stability parameters, and help document formula rationales referencing classical texts.",
        requiredSkills: ["Herbal Medicine", "Laboratory Skills", "Quality Control"],
        preferredSkills: ["Herbal Extraction", "GMP", "Product Development"],
        location: "New Delhi (Hybrid)",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Industry",
        status: "open",
        deadline: d(30),
        contactEmail: "rd@kamaayurveda.com",
        postedAt: p(2),
      },
      {
        title: "Bhasma QA/QC Laboratory Intern",
        organization: "Ayurveda Drug Testing Laboratory, Uttarakhand",
        description:
          "Perform routine quality control of Rasaushadhi samples — organoleptic evaluation, classical Bhasma tests (Varitara, Rekhapurna), and heavy-metal screening — for government testing services.",
        requiredSkills: ["Rasashastra", "Quality Control", "Laboratory Skills"],
        preferredSkills: ["Analytical Chemistry", "HPLC", "Report Writing"],
        location: "Dehradun, Uttarakhand",
        duration: "6 months",
        stipend: "₹12,000/month",
        type: "Government",
        status: "open",
        deadline: d(50),
        contactEmail: "lab@ayushtestinguk.org",
        postedAt: p(5),
      },
      {
        title: "Swasthavritta Community Medicine Intern",
        organization: "Swasthya Gram Project, Mahatma Gandhi Institute of Medical Sciences, Wardha",
        description:
          "Deliver preventive-care modules combining Swasthavritta and public health in adopted villages, conduct health-habit surveys, and evaluate adoption of seasonal regimens in the community.",
        requiredSkills: ["Ayurvedic Medicine", "Community Health", "Data Collection"],
        preferredSkills: ["Public Health", "Social Work", "MS Excel"],
        location: "Wardha, Maharashtra",
        duration: "6 months",
        stipend: "₹9,000/month + Accommodation",
        type: "Research",
        status: "open",
        deadline: d(60),
        contactEmail: "swasthyagram@mgims.ac.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Tele-Consultation Documentation Intern",
        organization: "Tata 1mg — Ayurveda Online Consultation, Gurugram",
        description:
          "Review and structure Ayurvedic tele-consultation records, verify physician notes against standard treatment protocols, and help improve documentation templates for better clinical continuity.",
        requiredSkills: ["Ayurvedic Medicine", "Data Entry", "Communication"],
        preferredSkills: ["MS Excel", "Medical Writing", "Quality Control"],
        location: "Gurugram (Remote OK)",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open",
        deadline: d(25),
        contactEmail: "telemed@1mg.com",
        postedAt: p(1),
      },
      {
        title: "Rasayana Immune Health Clinical Intern",
        organization: "Sri Sri Tattva, Bengaluru",
        description:
          "Support clinical evaluation of immune-support Rasayana formulations — assist in participant screening, immunity-marker sample collection, and documentation of wellness outcome questionnaires.",
        requiredSkills: ["Clinical Research", "Ayurvedic Medicine", "Data Collection"],
        preferredSkills: ["Statistics", "SPSS", "Medical Writing"],
        location: "Bengaluru, Karnataka",
        duration: "6 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open",
        deadline: d(45),
        contactEmail: "clinical@srisritattva.in",
        postedAt: p(3),
      },
    ];

    let added = 0;
    for (const internship of internships) {
      if (have.has(internship.title.trim().toLowerCase())) continue;
      await ctx.db.insert("internships", internship);
      added += 1;
    }
    return added === 0 ? "already_seeded" : `seeded_${added}`;
  },
});
