import { mutation } from "./_generated/server";

// Seed 50 additional Ayurveda-related internships (appends to existing data)
export const seedMore = mutation({
  args: {},
  handler: async (ctx) => {
    // Count existing internships to avoid re-seeding
    const count = (await ctx.db.query("internships").collect()).length;
    if (count > 10) return "already_seeded";

    const now = Date.now();
    const d = (days: number) => now + days * 24 * 60 * 60 * 1000;
    const p = (days: number) => now - days * 24 * 60 * 60 * 1000;

    const internships = [
      {
        title: "Ayurvedic Toxicology & Pharmacovigilance Intern",
        organization: "Pharmacovigilance Programme for ASU&H Drugs (PvPI)",
        description:
          "Assist in monitoring adverse drug reactions of Ayurvedic medicines, contribute to signal detection reports, and help compile safety profiles for classical formulations. Learn regulatory pharmacovigilance in the AYUSH domain.",
        requiredSkills: ["Ayurvedic Medicine", "Rasashastra", "Report Writing"],
        preferredSkills: ["Pharmacovigilance", "Data Analysis", "Medical Writing", "SPSS"],
        location: "Gurugram, Haryana",
        duration: "6 months",
        stipend: "₹18,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(60),
        contactEmail: "pvpi@ipcindia.nic.in",
        postedAt: p(5),
      },
      {
        title: "Ayurveda Clinical Data Analyst Intern",
        organization: "All India Institute of Ayurveda (AIIA)",
        description:
          "Analyse clinical trial datasets from ongoing Ayurvedic intervention studies. Work with SAS/SPSS to clean data, run statistical tests, and prepare tables and figures for research manuscripts.",
        requiredSkills: ["Data Analysis", "Clinical Research", "Statistics"],
        preferredSkills: ["R", "SPSS", "SAS", "Medical Writing"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹20,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "research@aiia.gov.in",
        postedAt: p(3),
      },
      {
        title: "Herbal Pharmacognosy Lab Intern",
        organization: "National Institute of Pharmaceutical Education & Research (NIPER)",
        description:
          "Conduct microscopic and macroscopic evaluation of crude Ayurvedic drugs, assist in fingerprinting studies using HPTLC/HPLC, and document pharmacognostic standards for monographs.",
        requiredSkills: ["Pharmacognosy", "Herbal Medicine", "Laboratory Skills"],
        preferredSkills: ["HPTLC", "HPLC", "Phytochemistry", "Microscopy"],
        location: "SAS Nagar, Punjab",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "academics@niper.ac.in",
        postedAt: p(7),
      },
      {
        title: "Yoga Therapy Research Assistant",
        organization: "Swami Vivekananda Yoga Anusandhana Samsthana (S-VYASA)",
        description:
          "Support ongoing clinical studies evaluating yoga interventions for chronic diseases. Help collect physiological data (heart rate variability, cortisol levels), conduct participant interviews, and perform literature reviews.",
        requiredSkills: ["Yoga", "Research Methodology", "Data Collection"],
        preferredSkills: ["Statistics", "SPSS", "Academic Writing", "Physiology"],
        location: "Bengaluru",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "research@svyasa.org.in",
        postedAt: p(4),
      },
      {
        title: "Ayurvedic Cosmetics Product Development Intern",
        organization: "Forest Essentials",
        description:
          "Work with the product development team to formulate Ayurvedic skincare and haircare products. Assist in ingredient sourcing, stability studies, sensory evaluation, and regulatory documentation for cosmetic products.",
        requiredSkills: ["Herbal Medicine", "Quality Control", "Pharmacognosy"],
        preferredSkills: ["Cosmetic Science", "GMP", "Product Development", "HPLC"],
        location: "Dehradun, Uttarakhand",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(55),
        contactEmail: "careers@forestessentials.co.in",
        postedAt: p(6),
      },
      {
        title: "AYUSH Digital Infrastructure Intern",
        organization: "National Health Authority (ABHA Integration)",
        description:
          "Help integrate AYUSH health records into the Ayushman Bharat Digital Mission (ABDM). Work on data standards, API testing, and pilot evaluation of AYUSH clinical modules in the national health stack.",
        requiredSkills: ["Ayurvedic Medicine", "Data Entry", "MS Excel"],
        preferredSkills: ["Python", "API Testing", "Health Informatics", "Data Visualization"],
        location: "New Delhi (Hybrid)",
        duration: "3 months",
        stipend: "₹22,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(35),
        contactEmail: "abdm-intern@nha.gov.in",
        postedAt: p(2),
      },
      {
        title: "Panchakarma Research & Documentation Intern",
        organization: "Gujarat Ayurveda University (GAU)",
        description:
          "Document Panchakarma procedures, compile patient outcome data from the university hospital, and assist in drafting research protocols for upcoming clinical trials on Vamana and Basti therapies.",
        requiredSkills: ["Panchakarma", "Ayurvedic Medicine", "Literature Review"],
        preferredSkills: ["Academic Writing", "Data Entry", "Patient Care", "Statistics"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(70),
        contactEmail: "deptpanchakarma@gau.ac.in",
        postedAt: p(8),
      },
      {
        title: "Ayurveda Marketing & Content Intern",
        organization: "Baidyanath (D.S. Research Centre)",
        description:
          "Create content for Ayurveda product pages, social media, and educational blogs. Research Ayurvedic concepts, write SEO-optimized copy, and help design digital marketing campaigns for classical Ayurvedic products.",
        requiredSkills: ["Content Writing", "Digital Marketing", "Ayurvedic Medicine"],
        preferredSkills: ["SEO", "Social Media", "Graphic Design", "Canva"],
        location: "Kolkata",
        duration: "3 months",
        stipend: "₹11,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "marketing@baidyanath.com",
        postedAt: p(5),
      },
      {
        title: "Medicinal Plant Conservation Intern",
        organization: "Botanical Survey of India (BSI)",
        description:
          "Participate in field surveys documenting endangered medicinal plants used in Ayurveda. Collect herbarium specimens, GPS-tag plant habitats, and contribute to the red-list assessment of medicinal flora.",
        requiredSkills: ["Botany", "Herbal Medicine", "Laboratory Skills"],
        preferredSkills: ["GIS Mapping", "Photography", "Sanskrit", "Taxonomy"],
        location: "Kolkata / Various Field Sites",
        duration: "6 months",
        stipend: "₹16,000/month + Field Allowance",
        type: "Research",
        status: "open" as const,
        deadline: d(80),
        contactEmail: "recruitment@bsi.gov.in",
        postedAt: p(10),
      },
      {
        title: "Rasashastra & Bhaishajya Kalpana Intern",
        organization: "Institute of Post Graduate Teaching & Research in Ayurveda, Jamnagar",
        description:
          "Assist in the preparation and standardization of Rasaushadhis (mineral preparations). Learn traditional Shodhana and Marana procedures under expert guidance while documenting standardization protocols.",
        requiredSkills: ["Rasashastra", "Ayurvedic Medicine", "Laboratory Skills"],
        preferredSkills: ["Analytical Chemistry", "Quality Control", "GMP", "HPLC"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹12,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(60),
        contactEmail: "rasashastra@ipgtrau.edu.in",
        postedAt: p(9),
      },
      {
        title: "Ayurveda Gut Microbiome Research Intern",
        organization: "CSIR-Centre for Cellular & Molecular Biology (CCMB)",
        description:
          "Work on an interdisciplinary project studying the impact of Ayurvedic dietary regimens on gut microbiome composition. Assist in 16S rRNA sequencing, bioinformatics pipelines, and statistical analysis.",
        requiredSkills: ["Python", "Data Analysis", "Laboratory Skills"],
        preferredSkills: ["Bioinformatics", "Machine Learning", "Microbiology", "R"],
        location: "Hyderabad",
        duration: "6 months",
        stipend: "₹25,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "microbiome@ccmb.res.in",
        postedAt: p(4),
      },
      {
        title: "Prasuti Tantra & Stri Roga Clinical Intern",
        organization: "Sri Sri College of Ayurvedic Science & Research",
        description:
          "Observe and assist in obstetrics & gynecology OPD, learn Ayurvedic antenatal care protocols (Garbhini Paricharya), and document case studies on infertility management through Ayurvedic therapies.",
        requiredSkills: ["Prasuti Tantra", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Clinical Research", "Medical Writing", "Ultrasound Basics"],
        location: "Bengaluru",
        duration: "6 months",
        stipend: "₹8,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "gynecology@srisriayurveda.org",
        postedAt: p(3),
      },
      {
        title: "Ayurveda Supply Chain & Procurement Intern",
        organization: "Kerala State Drugs & Pharmaceuticals Ltd (KSDPL)",
        description:
          "Learn the end-to-end supply chain of raw herbs and finished Ayurvedic medicines. Assist in vendor evaluation, inventory management, procurement planning, and logistics coordination across government Ayurveda pharmacies.",
        requiredSkills: ["Herbal Medicine", "Data Entry", "MS Excel"],
        preferredSkills: ["Supply Chain Management", "SAP", "Report Writing", "Quality Control"],
        location: "Thiruvananthapuram, Kerala",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "procurement@ksdpl.com",
        postedAt: p(2),
      },
      {
        title: "Kayachikitsa Clinical Observership",
        organization: "National Ayurveda Research Institute for Panchakarma (NARIP)",
        description:
          "Observe outpatient and inpatient Kayachikitsa cases, assist in documentation of Nadi Pariksha findings, and compile evidence on chronic disease management through Ayurvedic internal medicine approaches.",
        requiredSkills: ["Kayachikitsa", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Research Methodology", "Data Collection", "Academic Writing"],
        location: "Thrissur, Kerala",
        duration: "3 months",
        stipend: "₹10,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "observership@narip.gov.in",
        postedAt: p(6),
      },
      {
        title: "Ayurvedic Neuroscience Research Intern",
        organization: "National Brain Research Centre (NBRC)",
        description:
          "Contribute to a project exploring the neuroprotective effects of Brahmi and Ashwagandha formulations. Assist with animal model handling, behavioural assays, and RT-PCR data analysis in a neuroscience lab.",
        requiredSkills: ["Laboratory Skills", "Ayurvedic Medicine", "Data Analysis"],
        preferredSkills: ["Cell Biology", "Python", "Statistics", "Phytochemistry"],
        location: "Manesar, Haryana",
        duration: "6 months",
        stipend: "₹22,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(55),
        contactEmail: "internships@nbrc.ac.in",
        postedAt: p(7),
      },
      {
        title: "AYUSH Health Economics Intern",
        organization: "National Institute of Health & Family Welfare (NIHFW)",
        description:
          "Analyse cost-effectiveness data from AYUSH versus conventional treatments for common lifestyle disorders. Build economic models, assist in health policy brief preparation, and support budget impact analyses.",
        requiredSkills: ["Data Analysis", "Report Writing", "Public Health"],
        preferredSkills: ["R", "SPSS", "Economics", "Power BI"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹18,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "health-econ@nihfw.org",
        postedAt: p(1),
      },
      {
        title: "Shalya Tantra Surgical Intern",
        organization: "Gujarat Ayurveda University Hospital",
        description:
          "Assist in Kshara Karma and Agni Karma procedures under supervision. Observe Kshara Sutra application for piles and fistula, document surgical cases, and learn pre-operative Ayurvedic preparation protocols.",
        requiredSkills: ["Shalya Tantra", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Surgical Techniques", "Medical Writing", "Anatomy"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "shalya@gauhospital.ac.in",
        postedAt: p(8),
      },
      {
        title: "Ayurveda EdTech Content Developer",
        organization: "Birla Ayurveda (KVK Group)",
        description:
          "Develop interactive digital learning content for Ayurveda students — video scripts, quizzes, infographics, and e-learning modules covering Dravyaguna, Rasa Shastra, and Kayachikitsa syllabi.",
        requiredSkills: ["Ayurvedic Medicine", "Content Writing", "Communication"],
        preferredSkills: ["Video Editing", "Canva", "Educational Design", "Hindi"],
        location: "Haridwar, Uttarakhand (Remote OK)",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "edtech@birlaayurveda.com",
        postedAt: p(4),
      },
      {
        title: "Shalakya Tantra ENT Research Intern",
        organization: "National Research Institute of Kayachikitsa (NRIM)",
        description:
          "Conduct research on Ayurvedic management of chronic sinusitis and tinnitus. Assist in patient recruitment, ENT examination documentation, and statistical analysis of treatment outcomes.",
        requiredSkills: ["Shalakya Tantra", "Ayurvedic Medicine", "Clinical Research"],
        preferredSkills: ["Statistics", "SPSS", "Literature Review", "Medical Writing"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(60),
        contactEmail: "shalakya@nrim.res.in",
        postedAt: p(5),
      },
      {
        title: "Ayurveda Gut Health Microbiome Intern",
        organization: "Center for Complementary & Integrative Health (CCIH), Jamnagar",
        description:
          "Work on a multi-centre study evaluating the impact of Ayurvedic Rasayana therapy on gut microbiome diversity. Collect stool samples, process DNA extractions, and assist in metagenomic data analysis.",
        requiredSkills: ["Laboratory Skills", "Ayurvedic Medicine", "Data Collection"],
        preferredSkills: ["Bioinformatics", "Python", "Microbiology", "Statistics"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹18,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "microbiome@ccih.ac.in",
        postedAt: p(3),
      },
      {
        title: "Ayurvedic Dietetics & Nutrition Intern",
        organization: "Rotary Aravind Eye Hospital — Nutrition Wing",
        description:
          "Assist in developing Ayurvedic diet plans for patients with metabolic disorders. Learn Ahara Vidhi Vidhana principles, conduct dietary assessments, and help prepare nutritional education materials.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Communication"],
        preferredSkills: ["Nutrition Science", "Diet Planning", "Data Entry", "Content Writing"],
        location: "Madurai, Tamil Nadu",
        duration: "3 months",
        stipend: "₹9,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(35),
        contactEmail: "nutrition@aravind.org",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Bioinformatics & Drug Design Intern",
        organization: "CSIR-Indian Institute of Chemical Technology (IICT)",
        description:
          "Apply molecular docking and virtual screening techniques to identify potential drug candidates from Ayurvedic plant databases. Work with Schrödinger suite and AutoDock on phytochemical libraries.",
        requiredSkills: ["Python", "Data Analysis", "Laboratory Skills"],
        preferredSkills: ["Bioinformatics", "Molecular Docking", "Chemoinformatics", "R"],
        location: "Hyderabad",
        duration: "6 months",
        stipend: "₹23,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "drugdesign@iict.res.in",
        postedAt: p(6),
      },
      {
        title: "Kaumarabhritya Pediatric Ayurveda Intern",
        organization: "Ashtamgai Ayurveda Hospital, Pune",
        description:
          "Assist in pediatric OPD, document growth & development milestones using Ayurvedic assessments (Bala Pariksha), and help prepare Krumi Chikitsa and Rasayana protocols for children.",
        requiredSkills: ["Kaumarabhritya", "Ayurvedic Medicine", "Patient Care"],
        preferredSkills: ["Pediatrics", "Data Collection", "Academic Writing"],
        location: "Pune, Maharashtra",
        duration: "3 months",
        stipend: "₹8,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "pediatrics@ashtamgai.org",
        postedAt: p(7),
      },
      {
        title: "Ayurveda Clinical Trials Coordinator",
        organization: "Rheumatology Research Foundation of India",
        description:
          "Coordinate multi-centre clinical trials evaluating Ayurvedic interventions in rheumatoid arthritis. Manage participant schedules, ensure GCP compliance, and maintain electronic case report forms.",
        requiredSkills: ["Clinical Research", "Report Writing", "Data Entry"],
        preferredSkills: ["GCP Certification", "REDCap", "SPSS", "Medical Writing"],
        location: "Mumbai",
        duration: "6 months",
        stipend: "₹20,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(55),
        contactEmail: "trials@rrfindia.org",
        postedAt: p(4),
      },
      {
        title: "Ayurveda Wellness App QA Intern",
        organization: "NirogStreet Inc.",
        description:
          "Test and quality-assure the NirogStreet Ayurveda telemedicine platform. Write test cases, report bugs, verify Ayurveda content accuracy, and assist in user acceptance testing for new feature launches.",
        requiredSkills: ["Quality Control", "Communication", "Data Entry"],
        preferredSkills: ["Software Testing", "JIRA", "API Testing", "Content Writing"],
        location: "New Delhi (Remote OK)",
        duration: "3 months",
        stipend: "₹15,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "qa@nirogstreet.com",
        postedAt: p(1),
      },
      {
        title: "Ayurveda Public Policy & Advocacy Intern",
        organization: "Lok Satta Movement — Health Policy Division",
        description:
          "Research AYUSH integration into primary healthcare, draft policy briefs, and prepare position papers on regulatory frameworks for Ayurvedic practice standardization in India.",
        requiredSkills: ["Public Health", "Report Writing", "Ayurvedic Medicine"],
        preferredSkills: ["Policy Analysis", "Academic Writing", "Data Visualization", "Power BI"],
        location: "Hyderabad / New Delhi",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(35),
        contactEmail: "policy@loksatta.org",
        postedAt: p(3),
      },
      {
        title: "Dravyaguna Ethnobotanical Survey Intern",
        organization: "Tropical Botanic Garden & Research Institute (TBGRI)",
        description:
          "Join field expeditions documenting traditional Dravyaguna knowledge from tribal communities in the Western Ghats. Collect ethnobotanical data, voucher specimens, and photograph medicinal plant habitats.",
        requiredSkills: ["Dravyaguna", "Botany", "Herbal Medicine"],
        preferredSkills: ["Ethnobotany", "Photography", "GIS Mapping", "Sanskrit"],
        location: "Thiruvananthapuram, Kerala",
        duration: "6 months",
        stipend: "₹14,000/month + Field Allowance",
        type: "Research",
        status: "open" as const,
        deadline: d(65),
        contactEmail: "ethnobotany@tbgri.kerala.gov.in",
        postedAt: p(9),
      },
      {
        title: "Ayurveda Social Media Manager Intern",
        organization: "Maharishi Ayurveda Products",
        description:
          "Manage Instagram, YouTube, and LinkedIn content calendars for Ayurveda product lines. Create reels, write captions, track engagement metrics, and collaborate on influencer campaigns.",
        requiredSkills: ["Digital Marketing", "Content Writing", "Communication"],
        preferredSkills: ["Social Media", "Video Editing", "Canva", "SEO"],
        location: "New Delhi (Hybrid)",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(25),
        contactEmail: "social@maharishiayurveda.in",
        postedAt: p(1),
      },
      {
        title: "Ayurvedic Toxicology Research Intern",
        organization: "Toxicology Division, National Institute of Pharmaceutical Sciences",
        description:
          "Assist in acute and sub-chronic toxicity studies of novel Ayurvedic formulations. Conduct histopathological analysis, compile dose-response data, and help prepare IND dossiers for regulatory submissions.",
        requiredSkills: ["Laboratory Skills", "Rasashastra", "Quality Control"],
        preferredSkills: ["Toxicology", "Histopathology", "SPSS", "Data Analysis"],
        location: "Panchkula, Haryana",
        duration: "6 months",
        stipend: "₹17,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "tox-intern@nips.ac.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Agronomy & Cultivation Intern",
        organization: "Indian Council of Agricultural Research (ICAR) — Aromatic & Medicinal Plants",
        description:
          "Support cultivation trials of key Ayurvedic medicinal plants (Ashwagandha, Tulsi, Brahmi). Collect agronomic data, conduct soil analysis, and help develop Good Agricultural Practices (GAP) protocols for herbal raw materials.",
        requiredSkills: ["Botany", "Laboratory Skills", "Data Entry"],
        preferredSkills: ["Agriculture", "Soil Science", "Statistics", "MS Excel"],
        location: "Kodagu, Karnataka",
        duration: "6 months",
        stipend: "₹15,000/month + Accommodation",
        type: "Research",
        status: "open" as const,
        deadline: d(70),
        contactEmail: "amp@icar.gov.in",
        postedAt: p(10),
      },
      {
        title: "Ayurveda Mental Health Research Intern",
        organization: "National Institute of Mental Health & Neuro Sciences (NIMHANS)",
        description:
          "Work on a project studying Ayurvedic interventions for anxiety and insomnia. Assist with PSG data collection, GAD-7/ISI questionnaire administration, and statistical analysis comparing Ayurvedic and conventional treatment arms.",
        requiredSkills: ["Clinical Research", "Data Collection", "Ayurvedic Medicine"],
        preferredSkills: ["Psychology", "SPSS", "Statistics", "Academic Writing"],
        location: "Bengaluru",
        duration: "6 months",
        stipend: "₹22,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "mental-health-ayurveda@nimhans.ac.in",
        postedAt: p(5),
      },
      {
        title: "Ayurvedic Supply Chain Traceability Intern",
        organization: "TRACES NXT (National Centre for Trade in Agriculture)",
        description:
          "Develop traceability frameworks for Ayurvedic herb supply chains using QR-based tracking. Learn blockchain fundamentals, assist in pilot testing, and prepare documentation for GACP compliance.",
        requiredSkills: ["Herbal Medicine", "Data Entry", "MS Excel"],
        preferredSkills: ["Blockchain", "Supply Chain Management", "Quality Control", "Python"],
        location: "New Delhi (Hybrid)",
        duration: "3 months",
        stipend: "₹16,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "traceability@tracesnxt.gov.in",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Data Visualization & Dashboard Intern",
        organization: "Ministry of AYUSH — Statistics Division",
        description:
          "Build interactive dashboards visualizing AYUSH infrastructure data across India — hospital counts, practitioner density, scheme utilization rates. Use Power BI/Tableau to present policy-relevant insights.",
        requiredSkills: ["Data Visualization", "MS Excel", "Report Writing"],
        preferredSkills: ["Power BI", "Tableau", "Python", "SQL"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹18,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(25),
        contactEmail: "stats@ayush.gov.in",
        postedAt: p(1),
      },
      {
        title: "Ayurveda Gut-Brain Axis Research Intern",
        organization: "Institute of Advanced Virology & Life Sciences (IAVLS)",
        description:
          "Investigate the gut-brain axis through Ayurvedic dietary interventions. Collect faecal samples, perform metagenomic sequencing, and analyse microbial diversity in the context of Ayurvedic Prakriti assessment.",
        requiredSkills: ["Laboratory Skills", "Python", "Data Analysis"],
        preferredSkills: ["Bioinformatics", "Microbiology", "Statistics", "R"],
        location: "Thiruvananthapuram, Kerala",
        duration: "6 months",
        stipend: "₹20,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "gutbrain@iavls.ac.in",
        postedAt: p(4),
      },
      {
        title: "Ayurveda Clinical Audit Intern",
        organization: "National Accreditation Board for Hospitals (NABH) — AYUSH Wing",
        description:
          "Assist in clinical audit and accreditation surveys of Ayurveda hospitals. Review patient records, verify SOP compliance, assess quality indicators, and prepare audit reports aligned with NABH-AYUSH standards.",
        requiredSkills: ["Quality Control", "Ayurvedic Medicine", "Report Writing"],
        preferredSkills: ["Clinical Auditing", "GCP", "Data Entry", "Communication"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹16,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(35),
        contactEmail: "audit@nabh.gov.in",
        postedAt: p(3),
      },
      {
        title: "Ayurveda Startup Operations Intern",
        organization: "Vicco Laboratories",
        description:
          "Support operations at a growing Ayurvedic FMCG company. Assist with demand forecasting, production scheduling, vendor coordination, and market analysis for Ayurvedic oral care and skincare product lines.",
        requiredSkills: ["MS Excel", "Communication", "Data Entry"],
        preferredSkills: ["Operations Management", "Supply Chain", "Digital Marketing", "SAP"],
        location: "Mumbai",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "operations@viccolabs.com",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Laser & Energy Medicine Intern",
        organization: "Centre for Laser & Energy Medicine, Jamnagar",
        description:
          "Explore the intersection of low-level laser therapy (LLLT) and Ayurvedic pain management. Assist in trial design, patient data collection, and literature review on Ayurveda-meets-modern-physiotherapy protocols.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Research Methodology"],
        preferredSkills: ["Biomedical Engineering", "Data Analysis", "Statistics", "SPSS"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹13,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(55),
        contactEmail: "laser@clerm.ac.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Heritage Documentation Intern",
        organization: "National Mission for Manuscripts (NMM) — Divya Brahmanda Division",
        description:
          "Digitize and catalog Ayurvedic palm-leaf manuscripts from private collections. Transcribe Sanskrit text, create metadata records, and contribute to an open-access digital repository of classical medical texts.",
        requiredSkills: ["Literature Review", "Data Entry", "Ayurvedic Medicine"],
        preferredSkills: ["Sanskrit", "Digitization", "Archival Science", "Content Writing"],
        location: "New Delhi / Varanasi",
        duration: "6 months",
        stipend: "₹15,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(60),
        contactEmail: "manuscripts@nmm.gov.in",
        postedAt: p(8),
      },
      {
        title: "Ayurveda Clinical Nutrition & Lifestyle Intern",
        organization: "Arogya World — NCD Prevention Initiative",
        description:
          "Help design Ayurveda-based lifestyle modification programs for diabetes prevention. Assist in community outreach, conduct dietary surveys using 24-hour recall, and analyse data for nutritional patterns.",
        requiredSkills: ["Ayurvedic Medicine", "Community Health", "Data Collection"],
        preferredSkills: ["Nutrition Science", "SPSS", "Public Health", "Content Writing"],
        location: "Bengaluru (Hybrid)",
        duration: "3 months",
        stipend: "₹12,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "programs@arogyaworld.org",
        postedAt: p(3),
      },
      {
        title: "Ayurvedic Herbal Garden & Research Intern",
        organization: "Rajiv Gandhi University of Health Sciences (RGUHS)",
        description:
          "Maintain the institutional medicinal plant garden, catalogue species, prepare herbarium sheets, and assist in pharmacognostic studies of plants used in classical Ayurvedic formulations.",
        requiredSkills: ["Botany", "Herbal Medicine", "Laboratory Skills"],
        preferredSkills: ["Taxonomy", "Photography", "HPTLC", "Data Entry"],
        location: "Bengaluru",
        duration: "6 months",
        stipend: "₹10,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(45),
        contactEmail: "garden@rguhs.ac.in",
        postedAt: p(7),
      },
      {
        title: "Ayurvedic Formulation Quality Lab Intern",
        organization: "State Drug Testing Laboratory, Kerala",
        description:
          "Analyze Ayurvedic patent medicines for heavy metals, microbial contamination, and phytochemical marker quantification. Perform AAS, ICP-OES, and HPLC testing under guidance of government chemists.",
        requiredSkills: ["Analytical Chemistry", "Laboratory Skills", "Quality Control"],
        preferredSkills: ["HPLC", "ICP-OES", "HPTLC", "GMP"],
        location: "Thiruvananthapuram, Kerala",
        duration: "6 months",
        stipend: "₹14,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(55),
        contactEmail: "qa@sdtl.kerala.gov.in",
        postedAt: p(5),
      },
      {
        title: "Ayurveda NAMA Scheme Implementation Intern",
        organization: "National AYUSH Mission (NAM) — Implementation Division",
        description:
          "Support scheme implementation for the National AYUSH Mission at the district level. Collect utilization data, prepare progress reports, and help evaluate the impact of AYUSH wellness centre establishment across rural India.",
        requiredSkills: ["Public Health", "Report Writing", "MS Excel"],
        preferredSkills: ["Data Visualization", "Power BI", "GIS Mapping", "Social Work"],
        location: "Multiple Districts (Field Posting)",
        duration: "6 months",
        stipend: "₹16,000/month + Travel Allowance",
        type: "Government",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "nam-intern@ayush.gov.in",
        postedAt: p(4),
      },
      {
        title: "Ayurveda Personalized Medicine Research Intern",
        organization: "CSIR-Indian Institute of Genomic & Integrative Biology (CSIR-IGIB)",
        description:
          "Work at the intersection of Ayurvedic Prakriti genomics and personalized medicine. Assist in genomic DNA extraction, SNP genotyping, and bioinformatics analysis correlating Prakriti types with genetic variants.",
        requiredSkills: ["Laboratory Skills", "Python", "Data Analysis"],
        preferredSkills: ["Genomics", "Bioinformatics", "R", "Machine Learning"],
        location: "New Delhi",
        duration: "6 months",
        stipend: "₹24,000/month",
        type: "Research",
        status: "open" as const,
        deadline: d(50),
        contactEmail: "prakriti@igib.res.in",
        postedAt: p(6),
      },
      {
        title: "Ayurveda Telemedicine Platform Intern",
        organization: "eSanjeevani AYUSH — MoHFW",
        description:
          "Assist in the expansion of AYUSH telemedicine services on the eSanjeevani platform. Help onboard Ayurveda practitioners, test video consultation modules, and prepare user training documentation.",
        requiredSkills: ["Ayurvedic Medicine", "Communication", "Data Entry"],
        preferredSkills: ["Telemedicine", "Software Testing", "Content Writing", "Hindi"],
        location: "New Delhi (Remote OK)",
        duration: "3 months",
        stipend: "₹16,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(20),
        contactEmail: "telehealth@esanjeevani.gov.in",
        postedAt: p(1),
      },
      {
        title: "Ayurvedic Dental Care Intern",
        organization: "Ayurvedic Dental College & Hospital, Gujarat",
        description:
          "Observe and assist in Ayurvedic management of periodontal diseases and oral submucous fibrosis. Learn Kavacha and Gandusha protocols, document clinical outcomes, and contribute to case-series publications.",
        requiredSkills: ["Ayurvedic Medicine", "Patient Care", "Clinical Research"],
        preferredSkills: ["Dentistry", "Medical Writing", "Data Collection", "Statistics"],
        location: "Jamnagar, Gujarat",
        duration: "6 months",
        stipend: "₹9,000/month",
        type: "Clinical",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "dental@ayurdental.ac.in",
        postedAt: p(5),
      },
      {
        title: "Ayurveda Research Grant Writer Intern",
        organization: "AYUSH Research Council — Extramural Research Division",
        description:
          "Assist investigators in writing competitive research grant proposals for AYUSH-funded projects. Review funding guidelines, prepare budget justifications, and compile literature review sections for ICRR and Extramural grant applications.",
        requiredSkills: ["Academic Writing", "Literature Review", "Report Writing"],
        preferredSkills: ["Grant Writing", "Research Methodology", "SPSS", "Data Visualization"],
        location: "New Delhi",
        duration: "3 months",
        stipend: "₹14,000/month",
        type: "Government",
        status: "open" as const,
        deadline: d(30),
        contactEmail: "grants@ayushresearch.gov.in",
        postedAt: p(2),
      },
      {
        title: "Ayurveda Mental Wellness App Content Intern",
        organization: "Practo — Ayurveda Vertical",
        description:
          "Write evidence-based Ayurveda content for the Practo wellness app — Prakriti assessment questionnaires, daily routine tips, seasonal regimen guides, and meditation scripts. Collaborate with Ayurvedic doctors for clinical accuracy.",
        requiredSkills: ["Ayurvedic Medicine", "Content Writing", "Communication"],
        preferredSkills: ["SEO", "UX Writing", "Social Media", "Canva"],
        location: "Bengaluru (Remote OK)",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(25),
        contactEmail: "content@practo.com",
        postedAt: p(1),
      },
      {
        title: "Ayurveda Forest & Tribal Medicine Documentation Intern",
        organization: "Tribal Cooperative Marketing Development Federation (TRIFED)",
        description:
          "Document traditional forest-based medicine knowledge from tribal healers in central India. Conduct Participatory Rural Appraisal (PRA), record ethnobotanical data, and help commercialize verified formulations through Van Dhan Vikas Kendras.",
        requiredSkills: ["Herbal Medicine", "Community Health", "Data Collection"],
        preferredSkills: ["Sociology", "Photography", "GIS Mapping", "Hindi"],
        location: "Bhopal / Field Sites, Madhya Pradesh",
        duration: "6 months",
        stipend: "₹15,000/month + Travel Allowance",
        type: "Government",
        status: "open" as const,
        deadline: d(65),
        contactEmail: "tribal-medicine@trifed.gov.in",
        postedAt: p(9),
      },
      {
        title: "Ayurveda Nutraceutical Regulatory Affairs Intern",
        organization: "Zandu Pharmaceutical Works (Emami Group)",
        description:
          "Assist the regulatory team in compiling dossiers for Ayurvedic nutraceutical products. Review label claims, track CDSCO and FSSAI compliance updates, and help prepare documentation for product license renewals.",
        requiredSkills: ["Ayurvedic Medicine", "Quality Control", "Report Writing"],
        preferredSkills: ["Regulatory Affairs", "GMP", "Documentation", "Communication"],
        location: "Kolkata, West Bengal",
        duration: "3 months",
        stipend: "₹13,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(40),
        contactEmail: "regulatory@zandu.in",
        postedAt: p(4),
      },
      {
        title: "Ayurveda Media & PR Communications Intern",
        organization: "Khadi Natural (The Ayurveda Company)",
        description:
          "Support media relations and public communications for an Ayurveda personal-care brand. Draft press releases about new herbal launches, coordinate PR events, and track media coverage of Ayurveda industry trends.",
        requiredSkills: ["Communication", "Content Writing", "Digital Marketing"],
        preferredSkills: ["Media Relations", "Social Media", "Event Management", "Report Writing"],
        location: "Bengaluru (Hybrid)",
        duration: "3 months",
        stipend: "₹11,000/month",
        type: "Industry",
        status: "open" as const,
        deadline: d(25),
        contactEmail: "pr@khadinatural.in",
        postedAt: p(2),
      },
    ];

    for (const internship of internships) {
      await ctx.db.insert("internships", internship);
    }

    return "seeded_50_more";
  },
});
